### ISSUE TITLE
Wiki, Fibers part: Can't evaluate provided example

### ISSUE THREAD

**Issue by honix** [bakpakin/janet#14]
```lisp
(def f (fiber/new (fn @[]
                   (yield 1)
                   (yield 2)
                   (yield 3)
                   (yield 4)
                   5)))
```
causes ```compile error in repl: expected function parameters```.

Seems like ```@[]``` -> ```[]``` works.

**Comment by bakpakin** [comment]
Yes, this is due to the changing language spec. I have update the language in various subtle ways since writing the intro, I forgot to update that one. Function args must now be tuples and cannot be arrays. I will update the introduction.
