### ISSUE TITLE
Initial Documentation

### ISSUE THREAD

**Issue by bakpakin** [bakpakin/janet#7]
Although Dst is in alpha (no feature is safe from being changed/deleted), some preliminary documentation is needed. Both the Dst language and the C source code need lots of documentation to help new contributors to the project.

**Comment by Gavlooth** [comment]
Could also benefit from a codex-like tool.

**Comment by bakpakin** [comment]
Documentation and a tutorial is a bit more fleshed out now. Also, documentation can be found via `(doc some-symbol)` in repl for api docs on a per function basis.
