### ISSUE TITLE
Initial Tutorial/Getting Started

### ISSUE THREAD

**Issue by bakpakin** [bakpakin/janet#8]
Dst needs an on-ramp for new contributors and users getting started. A simple tutorial for setting up Dst, using the repl, writing programs, and using the core functions would help newcomers understand the language without looking at all of the source code.

**Comment by Gavlooth** [comment]
I good tutorial needs some simple program to implement. Probably we have to be clear for the use cases of dst, and i think now that i can write a small program to facilitate that. The question is what would be that?

**Comment by bakpakin** [comment]
Dst is supposed to be general purpose, but a simple program could be perhaps a spellchecker or a minimax game ai, as with chess or checkers for something interesting. 

The spellchecker is nice because it could require reading and parsing data from a file, as well as some not too complex logic and use of core data structures.

**Comment by bakpakin** [comment]
There is an initial introduction and better docs currently. Closing this out.
